FROM jenkins/jenkins:lts
LABEL maintainer="a.svarych@gmail.com"

USER root
RUN apt-get update && apt-get install openjdk-11-jre-headless python3 python3-pip vim wget mc docker-compose -y
RUN ln /usr/bin/python3 /usr/bin/python
ADD requirements.jenkins .
RUN python -m pip install --upgrade pip setuptools wheel
RUN pip install --upgrade -r requirements.jenkins

ADD install_allure.py .
RUN python install_allure.py